/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProjectId = string;
export type CompanyName = string;
export type UserRole = string;
export type Mode = "discover_opportunities" | "evaluate_idea" | "strategy_question" | "compare_competitors";
export type CreatedAt = string;
export type ProjectStatus = "researching" | "ready" | "report_generated";
export type CompanyName1 = string;
export type KnownTicker = string | null;
export type ResearchTasks = string[];
export type SearchQueries = string[];
export type MinOfficialSources = number;
export type MinCompetitorSources = number;
export type MinIndustrySources = number;
export type SourceId = string;
export type Url = string;
export type Title = string;
export type Publisher = string | null;
export type PublishedDate = string | null;
export type SourceType = "official" | "filing" | "news" | "analyst" | "vendor" | "blog" | "academic" | "job_posting";
export type Confidence = number;
export type ClaimsExtracted = string[];
export type Name = string;
export type Ticker = string | null;
export type Website = string | null;
export type Headquarters = string | null;
export type CompanyType = string | null;
export type Industry = string | null;
export type Subindustries = string[];
export type BusinessSegments = string[];
export type OperatingRegions = string[];
export type Confidence1 = number;
export type RevenueLatest = number | null;
export type NetIncomeLatest = number | null;
export type MarketCap = number | null;
export type CapexLatest = number | null;
export type FinancialTrendSummary = string;
export type SourceRefs = string[];
export type Themes = string[];
export type EarningsCallSignals = string[];
export type InvestorPresentationSignals = string[];
export type SourceRefs1 = string[];
export type CompanyAiInitiatives = string[];
export type DigitalTransformationSignals = string[];
export type AutomationSignals = string[];
export type DataPlatformSignals = string[];
export type JobPostingSignals = string[];
export type PartnershipSignals = string[];
export type SourceRefs2 = string[];
export type DirectCompetitors = string[];
export type OperatorPeers = string[];
export type ServiceCompanyBenchmarks = string[];
export type TechnologyVendorBenchmarks = string[];
export type AdjacentIndustryBenchmarks = string[];
export type Company = string;
/**
 * Peer classification. Mislabeling a peer is a correctness bug (spec §3.3).
 */
export type PeerType =
  | "direct_competitor"
  | "operator_peer"
  | "service_company"
  | "technology_vendor"
  | "supplier"
  | "customer"
  | "adjacent_benchmark";
export type Signal = string;
export type AiArea = string;
export type BusinessRelevance = string;
export type Level = "low" | "medium" | "high";
export type SourceIds = string[];
export type Confidence2 = number;
export type CompetitiveAiSignals = CompetitiveSignal[];
export type IndustryAiPatterns = string[];
export type OpportunityHypotheses = string[];
export type Overall = number;
export type CompanyIdentity1 = number;
export type Financials = number;
export type PeerTaxonomy1 = number;
export type AiSignals = number;
export type OpportunityHypotheses1 = number;
export type Sources = string[];
export type Name1 = string;
export type Category = string;
export type ExecutiveSummary = string;
export type WhyNow = string;
export type CompetitivePressure = string;
export type TimeToPilot = "30_days" | "60_days" | "90_days" | "longer";
export type RecommendedFirstStep = string;
export type OverallScore = number;
export type Recommendation = "proceed" | "limited_pilot" | "needs_discovery" | "defer" | "not_recommended";
export type BusinessValue = number;
export type WorkflowClarity = number;
export type DataReadiness = number;
export type RiskControls = number;
export type EvaluationReadiness = number;
export type IntegrationFeasibility = number;
export type OperationalOwnership = number;
export type UserAdoption = number;
export type Blockers = string[];
export type Strengths = string[];
export type NextActions = string[];
export type CompanyName2 = string;
export type UserRole1 = string;
export type CompanyName3 = string;
export type IsSample = boolean;
export type WhatMatters = string;
export type CompetitivePressure1 = string;
export type TheOpening = string;
export type RecommendedNextMove = string;
export type Opportunities = OpportunityCard[];

export interface AIReadinessLabModels {
  Project?: Project;
  CompanyResearchPlan?: CompanyResearchPlan;
  SourceRecord?: SourceRecord;
  CompanyIntelligenceProfile?: CompanyIntelligenceProfile;
  CompetitiveSignal?: CompetitiveSignal;
  OpportunityCard?: OpportunityCard;
  ReadinessScorecard?: ReadinessScorecard;
  CreateProjectRequest?: CreateProjectRequest;
  BriefResponse?: BriefResponse;
}
export interface Project {
  project_id?: ProjectId;
  company_name: CompanyName;
  user_role: UserRole;
  mode: Mode;
  created_at?: CreatedAt;
  status?: ProjectStatus;
}
export interface CompanyResearchPlan {
  company_name: CompanyName1;
  known_ticker?: KnownTicker;
  research_tasks?: ResearchTasks;
  search_queries?: SearchQueries;
  source_requirements?: SourceRequirements;
}
export interface SourceRequirements {
  min_official_sources?: MinOfficialSources;
  min_competitor_sources?: MinCompetitorSources;
  min_industry_sources?: MinIndustrySources;
}
export interface SourceRecord {
  source_id?: SourceId;
  url: Url;
  title: Title;
  publisher?: Publisher;
  published_date?: PublishedDate;
  source_type: SourceType;
  confidence: Confidence;
  claims_extracted?: ClaimsExtracted;
}
export interface CompanyIntelligenceProfile {
  company_identity: CompanyIdentity;
  financial_snapshot?: FinancialSnapshot;
  strategic_priorities?: StrategicPriorities;
  ai_and_digital_signals?: AIDigitalSignals;
  peer_taxonomy?: PeerTaxonomy;
  competitive_ai_signals?: CompetitiveAiSignals;
  industry_ai_patterns?: IndustryAiPatterns;
  opportunity_hypotheses?: OpportunityHypotheses;
  confidence?: ProfileConfidence;
  sources?: Sources;
}
export interface CompanyIdentity {
  name: Name;
  ticker?: Ticker;
  website?: Website;
  headquarters?: Headquarters;
  company_type?: CompanyType;
  industry?: Industry;
  subindustries?: Subindustries;
  business_segments?: BusinessSegments;
  operating_regions?: OperatingRegions;
  confidence?: Confidence1;
}
export interface FinancialSnapshot {
  revenue_latest?: RevenueLatest;
  net_income_latest?: NetIncomeLatest;
  market_cap?: MarketCap;
  capex_latest?: CapexLatest;
  financial_trend_summary?: FinancialTrendSummary;
  source_refs?: SourceRefs;
}
export interface StrategicPriorities {
  themes?: Themes;
  earnings_call_signals?: EarningsCallSignals;
  investor_presentation_signals?: InvestorPresentationSignals;
  source_refs?: SourceRefs1;
}
export interface AIDigitalSignals {
  company_ai_initiatives?: CompanyAiInitiatives;
  digital_transformation_signals?: DigitalTransformationSignals;
  automation_signals?: AutomationSignals;
  data_platform_signals?: DataPlatformSignals;
  job_posting_signals?: JobPostingSignals;
  partnership_signals?: PartnershipSignals;
  source_refs?: SourceRefs2;
}
export interface PeerTaxonomy {
  direct_competitors?: DirectCompetitors;
  operator_peers?: OperatorPeers;
  service_company_benchmarks?: ServiceCompanyBenchmarks;
  technology_vendor_benchmarks?: TechnologyVendorBenchmarks;
  adjacent_industry_benchmarks?: AdjacentIndustryBenchmarks;
}
export interface CompetitiveSignal {
  company: Company;
  peer_type: PeerType;
  signal: Signal;
  ai_area: AiArea;
  business_relevance: BusinessRelevance;
  fomo_strength: Level;
  source_ids?: SourceIds;
  confidence: Confidence2;
}
export interface ProfileConfidence {
  overall?: Overall;
  company_identity?: CompanyIdentity1;
  financials?: Financials;
  peer_taxonomy?: PeerTaxonomy1;
  ai_signals?: AiSignals;
  opportunity_hypotheses?: OpportunityHypotheses1;
}
export interface OpportunityCard {
  name: Name1;
  category: Category;
  executive_summary: ExecutiveSummary;
  why_now: WhyNow;
  competitive_pressure: CompetitivePressure;
  business_value: Level;
  pilot_feasibility: Level;
  risk_level: Level;
  time_to_pilot: TimeToPilot;
  recommended_first_step: RecommendedFirstStep;
  technical_depth_required: Level;
}
export interface ReadinessScorecard {
  overall_score: OverallScore;
  recommendation: Recommendation;
  dimensions: ReadinessDimensions;
  blockers?: Blockers;
  strengths?: Strengths;
  next_actions?: NextActions;
}
export interface ReadinessDimensions {
  business_value: BusinessValue;
  workflow_clarity: WorkflowClarity;
  data_readiness: DataReadiness;
  risk_controls: RiskControls;
  evaluation_readiness: EvaluationReadiness;
  integration_feasibility: IntegrationFeasibility;
  operational_ownership: OperationalOwnership;
  user_adoption: UserAdoption;
}
export interface CreateProjectRequest {
  company_name: CompanyName2;
  user_role: UserRole1;
  mode: Mode;
}
/**
 * Executive AI Readiness Brief (spec §4.4).
 *
 * Phase 2 serves illustrative sample content so the shell is fully navigable;
 * real research replaces it in Phase 3. Text is framed as illustrative and
 * makes no factual claims about the company.
 */
export interface BriefResponse {
  company_name: CompanyName3;
  is_sample: IsSample;
  what_matters: WhatMatters;
  competitive_pressure: CompetitivePressure1;
  the_opening: TheOpening;
  recommended_next_move: RecommendedNextMove;
  opportunities: Opportunities;
}
